PATCH http://localhost:3001/tasks
Content-Type: application/json

 {
      "_id": "681c0fd0bbcbc2630df49a9c",
      "title": "Updated Task",
      "description": "This is a new task to be done",
      "status": "todo",
      "priority": "low",
      "dueDate": "2025-01-01T12:00:00.000Z",
      "createdAt": "2025-05-08T01:58:40.075Z",
      "updatedAt": "2025-05-08T01:58:40.075Z",
      "__v": 0
  }