POST http://localhost:3001/tasks
Content-Type: application/json

{
  "title": "Latest Title",
  "description": "This is a another new task to be done",
  "status": "todo",
  "priority": "low",
  "dueDate": "2025-01-01T12:00:00.000+00:00",
  "test": "test"
}