POST http://localhost:3001/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODU3ZmM4M2JjOWI5MmYwOTFkYTIwN2MiLCJlbWFpbCI6ImF6QGdtYWlsLmNvbSIsImlhdCI6MTc1MDg2NjkwOCwiZXhwIjoxNzUwOTUzMzA4fQ.Mf3T7mpJEb7rzbj9ouAYo6e6Ahd9lmZ5qLKzDlCYT8M

{
  "title": "New Task",
  "description": "A new task",
  "status": "todo",
  "priority": "low",
  "dueDate": "2025-01-01T12:00:00.000+00:00"
}